import type { NewJobInput } from "./jobs";

function daysAgo(n: number): string {
  return new Date(Date.now() - n * 86400_000).toISOString();
}

/**
 * Demo listings shown until the aggregation pipeline supplies real ones.
 * Companies are fictional; roles, salaries and locations mirror real market data.
 */
export const SEED_JOBS: NewJobInput[] = [
  {
    title: "Marine Diesel Technician",
    company: "Harborline Yacht Services",
    city: "Fort Lauderdale",
    state: "FL",
    category: "marine-technician",
    description:
      "Service and repair diesel propulsion systems on vessels 30–80ft. Diagnostics, repowers, scheduled maintenance and sea trials. Volvo Penta or Yanmar experience preferred; factory training provided. Full benefits, relocation assistance available.",
    salary_min: 65000,
    salary_max: 95000,
    certifications: ["ABYC Diesel", "Volvo Penta Certified"],
    posted_at: daysAgo(2),
  },
  {
    title: "Outboard Technician — Mercury/Yamaha",
    company: "Gulf Coast Marine Center",
    city: "Tampa",
    state: "FL",
    category: "marine-technician",
    description:
      "Busy dealership service department seeks certified outboard tech. Rigging, 100-hour services, warranty diagnostics on Mercury and Yamaha outboards. Flat-rate with guaranteed minimum.",
    salary_min: 30,
    salary_max: 45,
    salary_unit: "HOUR",
    certifications: ["Mercury Certified", "Yamaha Certified"],
    posted_at: daysAgo(5),
  },
  {
    title: "Marine Electrician",
    company: "Chesapeake Bay Boatworks",
    city: "Annapolis",
    state: "MD",
    category: "marine-electrician",
    description:
      "Install and troubleshoot AC/DC systems, battery banks, inverters, and NMEA 2000 networks on sail and power vessels. ABYC Electrical certification strongly preferred — we pay for recertification.",
    salary_min: 60000,
    salary_max: 85000,
    certifications: ["ABYC Electrical", "NMEA Installer"],
    posted_at: daysAgo(1),
  },
  {
    title: "Travel Lift Operator / Yard Lead",
    company: "Penobscot Marine Yard",
    city: "Rockland",
    state: "ME",
    category: "yard-staff",
    description:
      "Operate 75-ton travel lift, manage haul-out schedule, block and store vessels up to 60ft. Year-round position with winter storage program. Forklift and hydraulic trailer experience a plus.",
    salary_min: 22,
    salary_max: 30,
    salary_unit: "HOUR",
    certifications: [],
    posted_at: daysAgo(3),
  },
  {
    title: "Fiberglass / Gelcoat Repair Specialist",
    company: "Lakeshore Boat Restoration",
    city: "Traverse City",
    state: "MI",
    category: "fiberglass-repair",
    description:
      "Structural fiberglass repair, gelcoat color matching, blister work and barrier coats. Insurance and collision work — steady volume year round in heated shop.",
    salary_min: 25,
    salary_max: 38,
    salary_unit: "HOUR",
    certifications: [],
    posted_at: daysAgo(8),
  },
  {
    title: "Sailboat Rigger",
    company: "Narragansett Rigging Co.",
    city: "Newport",
    state: "RI",
    category: "rigger",
    description:
      "Standing and running rigging on race and cruising sailboats. Swaging, splicing, mast stepping, rig tuning and inspections. Climbing comfort required; America's Cup town, serious sailing clientele.",
    salary_min: 55000,
    salary_max: 78000,
    certifications: [],
    posted_at: daysAgo(4),
  },
  {
    title: "Marine Canvas Fabricator",
    company: "Bayfront Canvas & Interiors",
    city: "San Diego",
    state: "CA",
    category: "canvas-upholstery",
    description:
      "Pattern, cut and sew biminis, enclosures, and covers. Sunbrella and Strataglass experience preferred. Custom interior cushion work for sport fishers and cruisers.",
    salary_min: 24,
    salary_max: 34,
    salary_unit: "HOUR",
    certifications: [],
    posted_at: daysAgo(9),
  },
  {
    title: "Service Writer — Marine Dealership",
    company: "Lake Norman Boat Sales",
    city: "Cornelius",
    state: "NC",
    category: "service-writer",
    description:
      "Front-of-house service scheduling, estimates, warranty claims and customer communication for a 12-bay service department. Dealership or marine service background required.",
    salary_min: 48000,
    salary_max: 65000,
    certifications: [],
    posted_at: daysAgo(6),
  },
  {
    title: "Mobile Marine Technician",
    company: "Sound Marine Mobile Service",
    city: "Seattle",
    state: "WA",
    category: "marine-technician",
    description:
      "Run your own service van (provided) covering Puget Sound marinas. Engine service, electrical troubleshooting, winterization. Independent role for an experienced tech who likes variety.",
    salary_min: 70000,
    salary_max: 100000,
    certifications: ["ABYC Systems"],
    posted_at: daysAgo(2),
  },
  {
    title: "Marine Electronics Installer",
    company: "Gulfstream Electronics",
    city: "Charleston",
    state: "SC",
    category: "marine-electrician",
    description:
      "Install chartplotters, radar, autopilots, and audio systems on new builds and refits. NMEA 2000 network design and commissioning. Garmin/Raymarine dealer.",
    salary_min: 26,
    salary_max: 40,
    salary_unit: "HOUR",
    certifications: ["NMEA Installer"],
    posted_at: daysAgo(7),
  },
  {
    title: "Boat Detailer — Full Time",
    company: "Brightwork Boat Care",
    city: "Sarasota",
    state: "FL",
    category: "detailer",
    description:
      "Wash-downs, compounding, ceramic coating and teak restoration on vessels 25–70ft. No experience required — paid training, growth into management for the right person.",
    salary_min: 18,
    salary_max: 25,
    salary_unit: "HOUR",
    certifications: [],
    posted_at: daysAgo(1),
  },
  {
    title: "Yard Hand / Launch Crew (Seasonal → Permanent)",
    company: "Cape Ann Marine Basin",
    city: "Gloucester",
    state: "MA",
    category: "yard-staff",
    description:
      "Spring launch crew: bottom paint, commissioning, dock work. Strong performers convert to year-round positions in our service department — several of our techs started here.",
    salary_min: 19,
    salary_max: 24,
    salary_unit: "HOUR",
    certifications: [],
    posted_at: daysAgo(3),
  },
  {
    title: "Senior Marine Technician — Shop Foreman Track",
    company: "Inland Marine Group",
    city: "Austin",
    state: "TX",
    category: "marine-technician",
    description:
      "Lead tech for high-volume wake boat dealership. Malibu/MasterCraft experience valued. Mentor junior techs, own diagnostic escalations, move into foreman role within 12 months.",
    salary_min: 75000,
    salary_max: 105000,
    certifications: ["Mercury Certified"],
    posted_at: daysAgo(4),
  },
  {
    title: "Marine Systems Technician",
    company: "Door County Yacht Works",
    city: "Sturgeon Bay",
    state: "WI",
    category: "marine-technician",
    description:
      "Plumbing, HVAC, watermakers and generators on cruising yachts. Winter refit season in heated sheds, summer commissioning. ABYC Systems certification path funded.",
    salary_min: 58000,
    salary_max: 80000,
    certifications: ["ABYC Systems"],
    posted_at: daysAgo(10),
  },
  {
    title: "Rigging & Mast Shop Apprentice",
    company: "Down East Spars",
    city: "Portland",
    state: "ME",
    category: "rigger",
    description:
      "Learn the trade: wire and rod rigging, spar building and repair. No marine experience needed — mechanical aptitude and reliability required. Earn while you learn.",
    salary_min: 17,
    salary_max: 22,
    salary_unit: "HOUR",
    certifications: [],
    posted_at: daysAgo(12),
  },
  {
    title: "Gelcoat Finisher — New Builds",
    company: "Atlantic Custom Boats",
    city: "Wanchese",
    state: "NC",
    category: "fiberglass-repair",
    description:
      "Final finish work on custom sportfish builds. Spray gelcoat, wet sand, buff to show quality. Production boatbuilding experience preferred.",
    salary_min: 23,
    salary_max: 35,
    salary_unit: "HOUR",
    certifications: [],
    posted_at: daysAgo(15),
  },
  {
    title: "Marina Service Manager",
    company: "Lake of the Ozarks Marine",
    city: "Osage Beach",
    state: "MO",
    category: "service-writer",
    description:
      "Run a 15-person service operation: scheduling, parts, warranty, P&L responsibility. Marine or powersports service management background required. Relocation package.",
    salary_min: 70000,
    salary_max: 95000,
    certifications: [],
    posted_at: daysAgo(5),
  },
  {
    title: "Outboard Tech — Entry Level Welcome",
    company: "Bayou Marine Service",
    city: "Lafayette",
    state: "LA",
    category: "marine-technician",
    description:
      "Growing independent shop will train motivated mechanics on Suzuki and Honda outboards. Factory school within first year. Tool allowance after 90 days.",
    salary_min: 18,
    salary_max: 28,
    salary_unit: "HOUR",
    certifications: ["Suzuki Certified", "Honda Marine Certified"],
    posted_at: daysAgo(6),
  },
  {
    title: "Marine Electrician — Refit Projects",
    company: "Pacific Refit Group",
    city: "Newport Beach",
    state: "CA",
    category: "marine-electrician",
    description:
      "Full rewires and electronics integration on 50–100ft refit projects. Read schematics, build panels, commission systems. Top-of-market pay for ABYC-certified electricians.",
    salary_min: 80000,
    salary_max: 110000,
    certifications: ["ABYC Electrical"],
    posted_at: daysAgo(2),
  },
  {
    title: "Forklift / Dry Stack Operator",
    company: "Intracoastal Dry Storage",
    city: "Jupiter",
    state: "FL",
    category: "yard-staff",
    description:
      "Operate marine forklift (Wiggins/Taylor) in high-volume dry stack. Launch and retrieve up to 40 boats daily, weekend rotation. Clean driving record required, will certify.",
    salary_min: 20,
    salary_max: 27,
    salary_unit: "HOUR",
    certifications: [],
    posted_at: daysAgo(4),
  },
  {
    title: "Canvas & Upholstery Seamstress/Seamster",
    company: "North Shore Marine Canvas",
    city: "Chicago",
    state: "IL",
    category: "canvas-upholstery",
    description:
      "Industrial sewing on marine canvas and interiors. Great Lakes cruiser clientele, winter interior work keeps the shop busy year-round.",
    salary_min: 22,
    salary_max: 30,
    salary_unit: "HOUR",
    certifications: [],
    posted_at: daysAgo(11),
  },
  {
    title: "Boat Detailing Crew Lead",
    company: "Emerald Coast Detail Co.",
    city: "Destin",
    state: "FL",
    category: "detailer",
    description:
      "Lead a 3-person mobile detailing crew. Schedule routes, quality control, train new hires. Truck and equipment provided; bonus on monthly revenue.",
    salary_min: 45000,
    salary_max: 60000,
    certifications: [],
    posted_at: daysAgo(7),
  },
  {
    title: "Diesel Tech — Trawler Specialist",
    company: "Salish Sea Yacht Service",
    city: "Anacortes",
    state: "WA",
    category: "marine-technician",
    description:
      "Serve the Pacific Northwest trawler fleet: John Deere, Cummins, Yanmar service and repowers. Strong diagnostic skills; hydraulics and stabilizers a plus.",
    salary_min: 68000,
    salary_max: 92000,
    certifications: ["ABYC Diesel", "Yanmar Certified"],
    posted_at: daysAgo(9),
  },
  {
    title: "Service Technician — Pontoon & Sterndrive",
    company: "Twin Lakes Marine",
    city: "Brainerd",
    state: "MN",
    category: "marine-technician",
    description:
      "Service pontoons and sterndrives for a family dealership. Winterization season overtime, relaxed summers on the water. Mercury MerCruiser training provided.",
    salary_min: 24,
    salary_max: 36,
    salary_unit: "HOUR",
    certifications: ["Mercury Certified"],
    posted_at: daysAgo(13),
  },
];
